# Generated by Django 5.2.2 on 2025-09-18 23:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("results", "0012_alter_result_round_alter_result_time1_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Scramble",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event",
                    models.CharField(
                        choices=[
                            ("333", "3x3x3 Cube"),
                            ("222", "2x2x2 Cube"),
                            ("444", "4x4x4 Cube"),
                            ("555", "5x5x5 Cube"),
                            ("666", "6x6x6 Cube"),
                            ("777", "7x7x7 Cube"),
                            ("333bf", "3x3x3 Blindfolded"),
                            ("333fm", "3x3x3 Fewest Moves"),
                            ("333oh", "3x3x3 One-handed"),
                            ("minx", "Megaminx"),
                            ("pyram", "Pyraminx"),
                            ("clock", "Clock"),
                            ("skewb", "Skewb"),
                            ("sq1", "Square One"),
                            ("444bf", "4x4x4 Blindfolded"),
                            ("555bf", "5x5x5 Blindfolded"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "round",
                    models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
                ),
                (
                    "scramble_num",
                    models.IntegerField(verbose_name=django.core.validators.MinValueValidator(-2)),
                ),
                ("scramble", models.TextField()),
                ("visible", models.BooleanField(default=False)),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scramble",
                        to="results.competition",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("competition", "event", "round", "scramble_num"),
                        name="unique_scramble_per_competition_event_round",
                    ),
                ],
            },
        ),
    ]
