# Generated by Django 5.2.2 on 2025-09-19 00:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("results", "0012_alter_result_round_alter_result_time1_and_more"),
        ("scrambles", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="scramble",
            name="unique_scramble_per_competition_event_round",
        ),
        migrations.AddField(
            model_name="scramble",
            name="scramble_set",
            field=models.IntegerField(
                default=1, validators=[django.core.validators.MinValueValidator(1)]
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="scramble",
            name="scramble_num",
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(-2)]),
        ),
        migrations.AddConstraint(
            model_name="scramble",
            constraint=models.UniqueConstraint(
                fields=(
                    "competition",
                    "event",
                    "round",
                    "scramble_set",
                    "scramble_num",
                ),
                name="unique_scramble_per_competition_event_round",
            ),
        ),
    ]
