# Generated by Django 5.2.2 on 2025-09-19 04:57

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("results", "0013_alter_result_event"),
        (
            "scrambles",
            "0002_remove_scramble_unique_scramble_per_competition_event_round_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ScrambleSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event",
                    models.CharField(
                        choices=[
                            ("333", "3x3x3 Cube"),
                            ("222", "2x2x2 Cube"),
                            ("444", "4x4x4 Cube"),
                            ("555", "5x5x5 Cube"),
                            ("666", "6x6x6 Cube"),
                            ("777", "7x7x7 Cube"),
                            ("333bf", "3x3x3 Blindfolded"),
                            ("333fm", "3x3x3 Fewest Moves"),
                            ("333oh", "3x3x3 One-handed"),
                            ("minx", "Megaminx"),
                            ("pyram", "Pyraminx"),
                            ("clock", "Clock"),
                            ("skewb", "Skewb"),
                            ("sq1", "Square-One"),
                            ("444bf", "4x4x4 Blindfolded"),
                            ("555bf", "5x5x5 Blindfolded"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "round",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "scramble_set",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "generated_on",
                    models.DateTimeField(
                        default=django.db.models.functions.datetime.Now()
                    ),
                ),
                ("visible", models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="scramble",
            name="unique_scramble_per_competition_event_round",
        ),
        migrations.RemoveField(
            model_name="scramble",
            name="competition",
        ),
        migrations.RemoveField(
            model_name="scramble",
            name="event",
        ),
        migrations.RemoveField(
            model_name="scramble",
            name="round",
        ),
        migrations.RemoveField(
            model_name="scramble",
            name="visible",
        ),
        migrations.AddField(
            model_name="scrambleset",
            name="competition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scramble_sets",
                to="results.competition",
            ),
        ),
        migrations.AlterField(
            model_name="scramble",
            name="scramble_set",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scrambles",
                to="scrambles.scrambleset",
            ),
        ),
        migrations.AddConstraint(
            model_name="scramble",
            constraint=models.UniqueConstraint(
                fields=("scramble_set", "scramble_num"), name="unique_scramble_per_set"
            ),
        ),
        migrations.AddConstraint(
            model_name="scrambleset",
            constraint=models.UniqueConstraint(
                fields=("competition", "event", "round", "scramble_set"),
                name="unique_scramble_set_per_competition_event_round",
            ),
        ),
    ]
