# Generated by Django 6.0.5 on 2026-10-07 01:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scrambles", "0003_scrambleset_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scrambleset",
            name="event",
            field=models.CharField(
                choices=[
                    ("333", "3x3x3 Cube"),
                    ("222", "2x2x2 Cube"),
                    ("444", "4x4x4 Cube"),
                    ("555", "5x5x5 Cube"),
                    ("666", "6x6x6 Cube"),
                    ("777", "7x7x7 Cube"),
                    ("333bf", "3x3x3 Blindfolded"),
                    ("333fm", "3x3x3 Fewest Moves"),
                    ("333oh", "3x3x3 One-handed"),
                    ("minx", "Megaminx"),
                    ("pyram", "Pyraminx"),
                    ("clock", "Clock"),
                    ("skewb", "Skewb"),
                    ("sq1", "Square-One"),
                    ("444bf", "4x4x4 Blindfolded"),
                    ("555bf", "5x5x5 Blindfolded"),
                    ("fto", "Face Turning Octahedron"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="scrambleset",
            name="generated_on",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
