# Generated by Django 5.2.2 on 2025-08-22 01:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="is_uoft_student",
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
